package com.example.data.api

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.Base64
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.util.concurrent.TimeUnit

object GeminiService {

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"

    /**
     * Generate text analysis or completion using Gemini.
     * @param modelName e.g. "gemini-3.1-pro-preview" for complex tasks, "gemini-3.5-flash" for general tasks, "gemini-3.1-flash-lite-preview" for fast tasks.
     */
    suspend fun generateText(
        prompt: String,
        systemInstruction: String? = null,
        modelName: String = "gemini-3.5-flash",
        imageBitmap: Bitmap? = null
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val apiKey = try { BuildConfig.GEMINI_API_KEY } catch (e: Exception) { "" }
            if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
                return@withContext Result.failure(
                    IllegalStateException("Gemini API key is missing. Please set GEMINI_API_KEY in AI Studio Secrets.")
                )
            }

            val requestJson = JSONObject()
            val contentsArray = JSONArray()
            val contentObj = JSONObject()
            val partsArray = JSONArray()

            // Text part
            val textPart = JSONObject().put("text", prompt)
            partsArray.put(textPart)

            // Optional Image inline data
            if (imageBitmap != null) {
                val outputStream = ByteArrayOutputStream()
                imageBitmap.compress(Bitmap.CompressFormat.JPEG, 85, outputStream)
                val base64Image = Base64.encodeToString(outputStream.toByteArray(), Base64.NO_WRAP)

                val imagePart = JSONObject().put(
                    "inline_data", JSONObject()
                        .put("mime_type", "image/jpeg")
                        .put("data", base64Image)
                )
                partsArray.put(imagePart)
            }

            contentObj.put("parts", partsArray)
            contentsArray.put(contentObj)
            requestJson.put("contents", contentsArray)

            // System instruction if provided
            if (!systemInstruction.isNullOrBlank()) {
                val sysObj = JSONObject().put(
                    "parts", JSONArray().put(JSONObject().put("text", systemInstruction))
                )
                requestJson.put("systemInstruction", sysObj)
            }

            val mediaType = "application/json; charset=utf-8".toMediaType()
            val body = requestJson.toString().toRequestBody(mediaType)

            val targetModel = when (modelName) {
                "pro" -> "gemini-3.1-pro-preview"
                "lite" -> "gemini-3.1-flash-lite-preview"
                "flash" -> "gemini-3.5-flash"
                else -> modelName
            }

            val url = "$BASE_URL/$targetModel:generateContent?key=$apiKey"

            val request = Request.Builder()
                .url(url)
                .post(body)
                .build()

            val response = client.newCall(request).execute()
            val responseBody = response.body?.string()

            if (!response.isSuccessful || responseBody.isNullOrBlank()) {
                val errorMsg = JSONObject(responseBody ?: "{}")
                    .optJSONObject("error")?.optString("message") ?: "HTTP ${response.code}: ${response.message}"
                return@withContext Result.failure(Exception("Gemini API Error: $errorMsg"))
            }

            val json = JSONObject(responseBody)
            val candidates = json.optJSONArray("candidates")
            if (candidates != null && candidates.length() > 0) {
                val candidate = candidates.getJSONObject(0)
                val content = candidate.optJSONObject("content")
                val parts = content?.optJSONArray("parts")
                if (parts != null && parts.length() > 0) {
                    val text = parts.getJSONObject(0).optString("text", "")
                    return@withContext Result.success(text)
                }
            }

            Result.failure(Exception("No content generated by Gemini."))
        } catch (e: Exception) {
            e.printStackTrace()
            Result.failure(e)
        }
    }

    /**
     * Generate an image using Gemini Image Preview Models.
     * Models: "gemini-3.1-flash-image-preview" (general) or "gemini-3-pro-image-preview" (high quality)
     * Aspect ratios: 1:1, 2:3, 3:2, 3:4, 4:3, 9:16, 16:9, 21:9
     * Sizes: 1K, 2K, 4K
     */
    suspend fun generateImage(
        prompt: String,
        aspectRatio: String = "1:1",
        size: String = "1K",
        modelName: String = "gemini-3-pro-image-preview"
    ): Result<Bitmap> = withContext(Dispatchers.IO) {
        try {
            val apiKey = try { BuildConfig.GEMINI_API_KEY } catch (e: Exception) { "" }
            if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
                return@withContext Result.failure(
                    IllegalStateException("Gemini API Key missing. Please configure GEMINI_API_KEY in AI Studio Secrets.")
                )
            }

            val requestJson = JSONObject()
            val contentsArray = JSONArray()
            val contentObj = JSONObject()
            val partsArray = JSONArray()

            val enrichedPrompt = "Generate high quality document cover illustration: $prompt. Aspect ratio: $aspectRatio, Resolution: $size."
            partsArray.put(JSONObject().put("text", enrichedPrompt))

            contentObj.put("parts", partsArray)
            contentsArray.put(contentObj)
            requestJson.put("contents", contentsArray)

            // Generation config
            val genConfig = JSONObject()
                .put("responseMimeType", "image/jpeg")
            requestJson.put("generationConfig", genConfig)

            val mediaType = "application/json; charset=utf-8".toMediaType()
            val body = requestJson.toString().toRequestBody(mediaType)

            val url = "$BASE_URL/$modelName:generateContent?key=$apiKey"

            val request = Request.Builder()
                .url(url)
                .post(body)
                .build()

            val response = client.newCall(request).execute()
            val responseBody = response.body?.string()

            if (!response.isSuccessful || responseBody.isNullOrBlank()) {
                val errorMsg = JSONObject(responseBody ?: "{}")
                    .optJSONObject("error")?.optString("message") ?: "HTTP ${response.code}: ${response.message}"
                return@withContext Result.failure(Exception("Gemini Image API Error: $errorMsg"))
            }

            val json = JSONObject(responseBody)
            val candidates = json.optJSONArray("candidates")
            if (candidates != null && candidates.length() > 0) {
                val candidate = candidates.getJSONObject(0)
                val content = candidate.optJSONObject("content")
                val parts = content?.optJSONArray("parts")
                if (parts != null && parts.length() > 0) {
                    for (i in 0 until parts.length()) {
                        val part = parts.getJSONObject(i)
                        val inlineData = part.optJSONObject("inlineData") ?: part.optJSONObject("inline_data")
                        if (inlineData != null) {
                            val base64Data = inlineData.optString("data")
                            if (base64Data.isNotBlank()) {
                                val imageBytes = Base64.decode(base64Data, Base64.DEFAULT)
                                val bitmap = BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
                                if (bitmap != null) {
                                    return@withContext Result.success(bitmap)
                                }
                            }
                        }
                    }
                }
            }

            Result.failure(Exception("Image generation payload did not contain valid image bytes."))
        } catch (e: Exception) {
            e.printStackTrace()
            Result.failure(e)
        }
    }
}
